# Notebook 2026 — Tracker (Fase 1, pre-CES)
# Nessuna logica di prezzo: priorità a rumor/news, certificazioni, major patch Windows.

feeds:
  # News/rumor generalisti
  - { url: "https://www.notebookcheck.net/newsfeed.986.xml", tag: "nbc" }
  - { url: "https://www.windowscentral.com/rss", tag: "win" }
  - { url: "https://www.neowin.net/news/rss/", tag: "win" }
  - { url: "https://blogs.windows.com/feed/", tag: "msft" }
  - { url: "https://www.theverge.com/rss/index.xml", tag: "gen" }
  - { url: "https://www.engadget.com/rss.xml", tag: "gen" }
  - { url: "https://www.tomshardware.com/feeds/all", tag: "hw" }
  - { url: "https://www.anandtech.com/rss", tag: "hw" }
  - { url: "https://www.xda-developers.com/feed/", tag: "gen" }

  # Brand principali (non solo Lenovo)
  - { url: "https://news.lenovo.com/feed/", tag: "brand" }
  - { url: "https://press.hp.com/us/en/rss/press-releases.rss", tag: "brand" }
  - { url: "https://www.dell.com/learn/us/en/uscorp1/rssfeeds", tag: "brand" }
  - { url: "https://press.asus.com/feed/", tag: "brand" }
  - { url: "https://globalpress.acer.com/feed/", tag: "brand" }
  - { url: "https://www.msi.com/rss", tag: "brand" }

  # Certificazioni/regolatori (FCC, 3C, RED/CE) – spesso rumor affidabili
  - { url: "https://fccid.io/feed", tag: "fcc" }
  # Per 3C/RED non sempre ci sono feed stabili: coperti via keyword su siti generalisti

# Must-match (almeno uno) per passare il gate hardware/OS (lasciamo passare FCC/strong)
must_match_any:
  # Display/resoluzione e pannello
  - "(?i)2560\\s?[×x]\\s?1600|wqxga|qhd\\+"
  - "(?i)matte|opaco|anti[-\\s]?glare"
  - "(?i)300\\s?nit|350\\s?nit|400\\s?nit"

  # Espandibilità e build
  - "(?i)ram\\s+(upgradable|expandable|so-dimm)"
  - "(?i)ssd|m\\.2|nvme|2tb|1tb"
  - "(?i)mil[-\\s]?std|chassis|magnesium|alloy|thinkpad|t\\d{3}|p\\d{3}"

  # I/O / biometria / webcam
  - "(?i)fingerprint|windows\\s+hello|ir\\s+camera"
  - "(?i)1080p\\s+webcam|4k\\s+webcam|privacy\\s+shutter"

  # Connettività
  - "(?i)802\\.11be|wifi\\s*7|bluetooth\\s*5\\.(3|4|5)"

include_keywords_positive:
  # Windows 11 big patch, 24H2, Copilot on Windows
  - "(?i)windows\\s*11\\s*(24h2|major update|feature update|build|patch|release)"
  - "(?i)copilot\\+|copilot on windows|hudson\\s+valley"
  # Nuove linee business/office
  - "(?i)elitebook|latitude|thinkbook|thinkpad|probook|travelmate|expertbook"
  # FCC/3C/RED leak
  - "(?i)fcc|fccid|\\b3c\\b|china\\s+compulsory\\s+certification|\\bred\\b|radio\\s+equipment\\s+directive|ce\\s+mark"

include_keywords_strong:
  # Windows 12 (rumor o leak), grandi annunci MS
  - "(?i)windows\\s*12|next\\s+version\\s+of\\s+windows"
  - "(?i)24h2\\b|hudson\\s+valley\\b"
  # Early certifications (doppio boost)
  - "(?i)granted\\s+by\\s+fcc|filed\\s+with\\s+fcc|type\\s+approval\\s+3c"

exclude_keywords:
  # Evita rumor clickbait e device non laptop
  - "(?i)smartphone|tablet|router|tv|gpu\\s+rumor|console"
  - "(?i)giveaway|coupon|discount|price\\s+drop|deal|affiliat"
  - "(?i)gaming\\s+benchmarks|mining"
  - "(?i)how\\s+to|guide|tutorial"   # rumore non news
  - "(?i)review|recensione"          # opzionale: se vuoi tenerle, rimuovi questa riga

trusted_hosts:
  - "(?i)notebookcheck\\.net"
  - "(?i)windowscentral\\.com"
  - "(?i)theverge\\.com"
  - "(?i)neowin\\.net"
  - "(?i)anandtech\\.com"
  - "(?i)tomshardware\\.com"
  - "(?i)blogs\\.windows\\.com"

low_quality_hosts:
  - "(?i)weibo\\.cn|reddit\\.com|facebook\\.com|tiktok\\.com|pinterest\\.com"

# Uscita
output_path: "public/news.json"
