meta:
  timezone: "Europe/Rome"
  run_days: [1, 15]
  window_days: 14

# --- COSA VOGLIO PRENDERE (ampio ma mirato)
include_keywords:
  # Brand / linea
  - "(?i)thinkpad"
  - "(?i)lenovo"
  - "(?i)latitude|elitebook|zbook|xps"   # altre linee business rilevanti

  # Windows / OS / release
  - "(?i)windows\\s?(11|12)"
  - "(?i)major update|release|build|patch|aggiornamento"
  - "(?i)copilot\\+|copilot on windows"
  - "(?i)24h2|hudson valley"

  # Generazioni / codici
  - "(?i)gen\\s?(5|6|7)"
  - "(?i)\\b(20|21)[A-Z0-9]{2}\\b"

  # Wireless / reti
  - "(?i)802\\.11be|wifi\\s*7"

  # Certificazioni / leak
  - "(?i)fcc|fccid"
  - "(?i)\\b3c\\b|china compulsory certification"
  - "(?i)\\bred\\b|radio equipment directive|ce mark"

  # --- Display target ---
  # Risoluzioni
  - "(?i)\\b2560\\s*[x×]\\s*1600\\b"
  - "(?i)\\b2560\\s*[x×]\\s*1440\\b"

  # Sinonimi marketing
  - "(?i)\\b(WQXGA|QHD\\+|2\\.5K|QHD|WQHD)\\b"

  # Luminosità target
  - "(?i)\\b(3[0-9]{2}|400)\\s*nits?\\b"

  # Finitura opaca
  - "(?i)\\b(anti-?glare|matte)\\b"

# --- COSA TAGLIO (rumore, promo, categorie non notebook)
exclude_keywords:
  # Gaming / intrattenimento
  - "(?i)ideapad|legion|gaming|xbox|playstation|dlc|assassin|mirage"

  # Promo / affiliazioni / deals
  - "(?i)coupon|expired|giveaway|promo|offerta|sconto"
  - "(?i)\\bdeal\\b"
  - "(?i)get .* for (just|only)\\b"
  - "(?i)license\\b"
  - "(?i)vpn\\b"

  # Categorie consumer non pertinenti
  - "(?i)phone|smartphone|tablet|xiaomi|huawei|oppo|vivo|oneplus|iphone|galaxy\\s?s\\d+"
  - "(?i)earbud|headset|speaker|tv|projector|camera|drone|washing|fridge|appliance"
  - "(?i)router\\b|smart home|iot\\b"

  # Rumore generico / social
  - "(?i)shitpost|meme|random|cat"

  # Risoluzioni da escludere
  - "(?i)\\b1920\\s*[x×]\\s*1080\\b|\\b1920\\s*[x×]\\s*1200\\b"  # FHD / FHD+
  - "(?i)\\b3840\\s*[x×]\\s*2400\\b|\\b3840\\s*[x×]\\s*2160\\b|\\b4K\\b|UHD\\+?"  # 4K/UHD

  # Pannelli o feature non volute
  - "(?i)\\bOLED\\b|\\bAMOLED\\b|\\bglossy\\b"
  - "(?i)RTX|GeForce|Radeon\\s*RX"

# --- FONTI AFFIDABILI
news_sources:
  - url: "https://www.notebookcheck.net/rss/news.xml"
  - url: "https://news.lenovo.com/feed/"
  - url: "https://blogs.windows.com/feed/"
  - url: "https://www.windowscentral.com/feed"
  - url: "https://www.neowin.net/news/rss"
  - url: "https://techreport.com/feed/"
  - url: "https://slashdot.org/rss/slashdotMain"
  - url: "https://laptopmedia.com/feed/"
  # Certificazioni FCC / leak
  - url: "https://fccid.io/feed"
  # Extra affidabili
  - url: "https://www.dell.com/en-us/blog/feed/"
  - url: "https://press.hp.com/us/en/rss.html"
  - url: "https://www.theverge.com/rss/index.xml"
  - url: "https://www.anandtech.com/rss/"
  - url: "https://www.pcmag.com/feeds/all"
  - url: "https://feeds.arstechnica.com/arstechnica/index/"

# --- Blocchi di sicurezza
domain_blocklist:
  - "ithome.com"
  - "mydrivers.com"

# Escludi automaticamente titoli con caratteri CJK
exclude_cjk: true
